# Generated by Django 3.2.17 on 2023-02-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('html', models.TextField()),
                ('css', models.TextField()),
                ('javascript', models.TextField()),
            ],
        ),
    ]
