# Generated by Django 3.2.17 on 2023-03-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_frontend_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontend',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
