# Generated by Django 3.2.17 on 2023-03-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_frontend_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='img_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
